-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`EMISORES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EMISORES` (
  `ID_EMISOR` INT NOT NULL,
  `NOMBRES_EMISOR` VARCHAR(30) NULL,
  `APELLIDOS_EMISOR` VARCHAR(30) NULL,
  `DOCUMENTO_IDENTIFICACION_EMISOR` VARCHAR(20) NULL,
  `CORREO_ELECTRONICO_EMISOR` VARCHAR(30) NULL,
  PRIMARY KEY (`ID_EMISOR`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BANCO_RECEPTOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BANCO_RECEPTOR` (
  `ID_BANCO_RECEPTOR` INT NOT NULL,
  `NOMBRE_BANCO_RECEPTOR` VARCHAR(30) NULL,
  `TELEFONO` VARCHAR(8) NULL,
  `DIRECCION` VARCHAR(45) NULL,
  `CORREO_CONTACTO` VARCHAR(30) NULL,
  PRIMARY KEY (`ID_BANCO_RECEPTOR`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`REMESAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`REMESAS` (
  `ID_REMESA` INT NOT NULL,
  `NOMBRE_RECPTOR` VARCHAR(30) NULL,
  `APELLIDOS_RECEPTOR` VARCHAR(30) NULL,
  `CORREO_RECEPTOR` VARCHAR(20) NULL,
  `DPI_RECEPTOR` VARCHAR(13) NULL,
  `MONTO` FLOAT NULL,
  `ESTADO_SAT` VARCHAR(10) NULL,
  `FECHA_ENVIO` DATETIME NULL,
  `FECHA_RECIBIDO` DATETIME NULL,
  `FECHA_PROCESADO` DATETIME NULL,
  `CORRELATIVO_REMESA` INT NULL,
  `EMISORES_ID_EMISOR` INT NOT NULL,
  `BANCO_RECEPTOR_ID_BANCO_RECEPTOR` INT NOT NULL,
  `ESTADO_BANCO_RECEPTOR` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_REMESA`),
  INDEX `fk_REMESAS_EMISORES_idx` (`EMISORES_ID_EMISOR` ASC),
  INDEX `fk_REMESAS_BANCO_RECEPTOR1_idx` (`BANCO_RECEPTOR_ID_BANCO_RECEPTOR` ASC),
  CONSTRAINT `fk_REMESAS_EMISORES`
    FOREIGN KEY (`EMISORES_ID_EMISOR`)
    REFERENCES `mydb`.`EMISORES` (`ID_EMISOR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_REMESAS_BANCO_RECEPTOR1`
    FOREIGN KEY (`BANCO_RECEPTOR_ID_BANCO_RECEPTOR`)
    REFERENCES `mydb`.`BANCO_RECEPTOR` (`ID_BANCO_RECEPTOR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
